services:
  postgres:
    image: docker.svc.assistance.bg:5000/postgres:16-alpine
    env_file: .env
    restart: always
    ports:
      - 127.0.0.1:5433:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
  linkwarden:
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres
    restart: always
    # build: . # uncomment to build from source
    image: docker.svc.assistance.bg:6000/assistance/linkwarden:latest # comment to build from source
    ports:
      - 6010:3000
    volumes:
      - ./data:/data/data
    depends_on:
      postgres:
        condition: service_healthy
      meilisearch:
        condition: service_started
  meilisearch:
    image: docker.svc.assistance.bg:5000/getmeili/meilisearch:v1.12.8
    restart: always
    ports:
      - 127.0.0.1:7710:7700
    env_file:
      - .env
    volumes:
      - ./meili_data:/meili_data
